MECHANISM_TERMS = {
    "self_powered": [
        "self-powered",
        "self powered",
        "self-sustainable",
        "self sustainable",
        "self-sustained",
        "self sustained",
        "self-charging",
        "self charging",
        "battery-free",
        "battery free",
        "batteryless",
        "battery-less",
        "without battery",
        "no battery",
        "without external power",
        "no external power",
        "external-power-free",
        "external power free",
        "power-source-free",
        "power source free",
        "power independent",
        "energy autonomous",
        "energy-autonomous",
        "energy self-sufficient",
        "energy self sufficient",
        "energy harvesting",
        "energy-harvesting",
    ],
    "tribo_or_friction": [
        "triboelectric",
        "tribo-electric",
        "triboelectricity",
        "triboelectrification",
        "triboelectric effect",
        "triboelectric nanogenerator",
        "teng",
        "contact electrification",
        "contact-electrification",
        "contact charging",
        "friction-induced",
        "friction induced",
        "frictional",
        "frictional electricity",
        "frictional electrification",
        "friction electrification",
        "sliding electrification",
        "mechanical friction",
        "contact-separation",
        "contact separation",
        "freestanding triboelectric-layer",
        "freestanding triboelectric layer",
        "sliding freestanding",
        "sliding-mode",
        "sliding mode",
        "electrostatic",
        "electrostatic induction",
        "electrostatic effect",
        "mechanical energy",
        "mechanical-to-electrical",
        "mechanical to electrical",
        "mechanical energy conversion",
    ],
    "discharge_or_em_generation": [
        "gas breakdown discharge",
        "gas discharge",
        "air breakdown",
        "dielectric breakdown",
        "electrical breakdown",
        "breakdown discharge",
        "breakdown-discharge",
        "breakdown signal",
        "discharge breakdown",
        "discharge breakdown signal",
        "triboelectric-discharge",
        "triboelectric discharge",
        "triboelectricity-induced discharge",
        "triboelectricity induced discharge",
        "discharge-induced",
        "discharge induced",
        "electrical discharge",
        "electric discharge",
        "electrostatic discharge",
        "high-voltage discharge",
        "high voltage discharge",
        "arc discharge",
        "adaptive arc discharge",
        "spark discharge",
        "microspark",
        "micro-spark",
        "corona discharge",
        "microgap discharge",
        "micro-gap discharge",
        "microplasma",
        "micro-plasma",
        "plasma discharge",
        "transient discharge",
        "maxwell's displacement current",
        "maxwell’s displacement current",
        "maxwells displacement current",
        "displacement current",
        "instantaneous current generation",
        "high-frequency electromagnetic",
        "high frequency electromagnetic",
        "friction-induced electromagnetic",
        "friction induced electromagnetic",
        "electromagnetic wave",
        "electromagnetic waves",
        "electromagnetic radiation",
        "electromagnetic emission",
        "electromagnetic pulse",
        "em wave",
        "em waves",
        "em radiation",
        "em emission",
        "em pulse",
        "radio-frequency emission",
        "radio frequency emission",
        "rf emission",
        "uhf emission",
        "wireless electromagnetic",
        "breakdown",
        "spark",
        "corona",
        "microplasma",
        "discharge",
    ],
    "wireless_or_communication": [
        "wireless",
        "communication",
        "telemetry",
        "remote sensing",
        "remote monitoring",
        "long-range",
        "long range",
        "long-distance",
        "long distance",
        "transmission distance",
        "signal transmission",
        "wireless transmission",
        "data transmission",
        "encrypted signal transmission",
        "information encoding",
        "information transmission",
        "wireless communication",
        "wireless readout",
        "remote readout",
        "readout distance",
        "radio",
        "radio-frequency",
        "radio frequency",
        "uhf",
        "microwave",
        "antenna",
        "receiver",
        "reader",
        "lc resonator",
        "rlc",
        "resonator",
        "frequency modulation",
        "frequency-modulated",
        "passive wireless",
        "battery-free wireless",
        "batteryless wireless",
        "chip-less",
        "chipless",
    ],
    "sensing_or_system": [
        "sensor",
        "sensing",
        "monitoring",
        "detection",
        "measurement",
        "readout",
        "wearable",
        "wearable sensing",
        "motion sensing",
        "health monitoring",
        "patch",
        "electronic patch",
        "textile",
        "fabric",
        "e-textile",
        "haptic",
        "electrotactile",
        "human-machine",
        "human machine",
        "human–machine",
        "interface",
        "hmi",
        "stimulation",
        "flowmeter",
        "flow meter",
        "oil quality",
        "smart home",
        "pressure",
        "strain",
        "motion",
        "humidity",
        "temperature",
        "biomechanic",
        "biomimetic",
    ],
}
